### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pruett** [SimonDegraeve/hapi-webpack-plugin#6]
I receive the following error when trying to load up the plugin. Any idea what this might be pointing to? I'm assuming this has something to do with hapi and webpack as I don't receive information otherwise. Apologies if this is not related to the plugin.

``` bash
> babel-node lib/server.js

/Users/kevinpruett/Code/clab/node_modules/tapable/lib/Tapable.js:164
        arguments[i].apply(this);
                    ^

TypeError: Cannot read property 'apply' of undefined
    at Compiler.apply (/Users/kevinpruett/Code/clab/node_modules/tapable/lib/Tapable.js:164:15)
    at OptionsApply.WebpackOptionsApply.process (/Users/kevinpruett/Code/clab/node_modules/webpack/lib/WebpackOptionsApply.js:62:18)
    at new webpack (/Users/kevinpruett/Code/clab/node_modules/webpack/lib/webpack.js:22:48)
    at Object.<anonymous> (server.js:10:18)
    at Module._compile (module.js:397:26)
    at loader (/Users/kevinpruett/Code/clab/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kevinpruett/Code/clab/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at /Users/kevinpruett/Code/clab/node_modules/babel-cli/lib/_babel-node.js:161:27
    at Object.<anonymous> (/Users/kevinpruett/Code/clab/node_modules/babel-cli/lib/_babel-node.js:162:7)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by pruett** [comment]
this was a webpack issue, not specific to this plugin...sorry for opening this ticket. i was apparently trying to register a non-plugin into webpack which resulted in the above error.
